name: "CMake Lint"

on:
  pull_request:
    branches: [ main ]
    paths:
      - '**/CMakeLists.txt'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: "cmake lint"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
            sudo apt update -y
            sudo apt -y --no-install-recommends install \
              python3-pip='22.*'
            pip install cmakelint
      - name: Execute cmakelint
        run: find . \( \( -path './build' -o -path '*/.*' \) -prune \) -o
          \( -type f -a -iname 'CMakeLists.txt' \)
          -exec echo "Linting '{}'..." \;
          -exec cmakelint --spaces=1 {} +
