name: "C++ Build"

on:
  push:
    paths-ignore:
      - 'README.md'

jobs:
  build:
    name: "gcc/clang build"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cpp17_compatibility: [ "ON", "OFF" ]
        cpp_compiler: [ "g++", "clang++" ]
    steps:
      - uses: actions/checkout@v3
      - uses: jirutka/setup-alpine@v1
        with:
          branch: v3.19
      - name: Install dependencies
        run: |
            apk update
            apk add \
              cmake \
              ninja-build \
              g++ \
              clang \
              boost-dev \
              boost-filesystem \
              boost-python3 \
              lua5.2-dev \
              python3-dev \
              fmt-dev \
              gtest-dev
        shell: alpine.sh --root {0}
      - name: Prepare
        run: |
            CXX=/usr/bin/${{ matrix.cpp_compiler }} \
              cmake . -B build -G Ninja \
              -DCMAKE_MAKE_PROGRAM=/usr/lib/ninja-build/bin/ninja \
              -DCMAKE_BUILD_TYPE=Debug \
              -DPPPLUGIN_SHARED=ON \
              -DPPPLUGIN_ENABLE_EXAMPLES=ON \
              -DPPPLUGIN_ENABLE_TESTS=ON \
              -DPPPLUGIN_ENABLE_CPP17_COMPATIBILITY=${{ matrix.cpp17_compatibility }}
        shell: alpine.sh {0}
      - name: Build
        run: |
          cmake --build build -j
        shell: alpine.sh {0}
      - name: Install
        run: |
          cmake --install build
        shell: alpine.sh --root {0}
