name: "C++/CMake Format"

on:
  pull_request:
    branches: [ main ]
    paths:
      - '**/*.cpp'
      - '**/*.h'
      - '**/CMakeLists.txt'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  format:
    name: "clang-format/cmake-format"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: jirutka/setup-alpine@v1
        with:
          branch: v3.19
      - name: Install dependencies
        run: |
            apk update
            apk add \
              clang-extra-tools \
              py3-pip
            pip install --break-system-packages cmake-format
        shell: alpine.sh --root {0}
      # Check all source and header C++ files; ignore files in hidden directories
      - name: Execute clang-format
        run: find . \( -path '*/.*' -prune \) -o
          \( -type f -a \( -iname '*.cpp' -o -iname '*.h' \) \)
          -exec echo "Format checking '{}'..." \;
          -exec clang-format --dry-run --Werror --Wno-error=unknown {} +
        shell: alpine.sh {0}
      # Check all cmake files; ignore files in hidden directories
      - name: Execute cmake-format
        run: find . \( -path '*/.*' -prune \) -o
          \( -type f -a -name 'CMakeLists.txt' \)
          -exec echo "Format checking '{}'..." \;
          -exec cmake-format --check -- {} +
        shell: alpine.sh {0}
